server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/policydb
    username: policy_user
    password: policy_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: claims-kafka:9092
    consumer:
      group-id: policy-service

  profiles:
    default: rest

policies:
  events:
    evaluation-topic-name: policies.policy-evaluation-events

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  metrics:
    distribution:
      percentiles-histogram:
        policies.rest.latency: true
        policies.grpc.latency: true
        policies.kafka.consumer.latency: true
        policies.events.publish.latency: true

      percentiles:
        policies.rest.latency: 0.5, 0.95, 0.99
        policies.grpc.latency: 0.5, 0.95, 0.99
        policies.kafka.consumer.latency: 0.5, 0.95, 0.99
        policies.events.publish.latency: 0.5, 0.95, 0.99

grpc:
  server:
    port: 9191