global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Spring Boot Claim-Service (läuft auf dem Host, Port 8080)
  - job_name: "claim-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  # Spring Boot Policy-Service
  - job_name: 'policy-service'
    static_configs:
      - targets: ['host.docker.internal:8081']

  # Prometheus selbst (optional, nützlich zum Debuggen)
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
