spring:
  application:
    name: claims-service

  datasource:
    url: jdbc:postgresql://localhost:5432/claimsdb
    username: claims_user
    password: claims_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    bootstrap-servers: claims-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    template:
      default-topic: claims.claim-events

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  metrics:
    distribution:
      percentiles-histogram:
        claims.rest.latency: true
        claims.grpc.latency: true
        claims.kafka.producer.latency: true
        claims.service.operation.duration: true

      percentiles:
        claims.rest.latency: 0.5, 0.95, 0.99
        claims.grpc.latency: 0.5, 0.95, 0.99
        claims.kafka.producer.latency: 0.5, 0.95, 0.99
        claims.service.operation.duration: 0.5, 0.95, 0.99
